- name: Установка мониторинга на серверы
  hosts: servers
  become: yes
  tasks:

    - name: Установка пакетов
      apt:
        name:
          - curl
          - tar
          - docker.io
        state: present
        update_cache: yes

    - name: Установка экспортера
      ansible.builtin.shell: |
        curl -LO https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
        tar xvf node_exporter-1.7.0.linux-amd64.tar.gz
        mv node_exporter-1.7.0.linux-amd64/node_exporter /usr/local/bin/
        rm -rf node_exporter-1.7.0.linux-amd64*
      args:
        creates: /usr/local/bin/node_exporter

    - name: Создание systemd-юнита для экспортера
      copy:
        dest: "/etc/systemd/system/node_exporter.service"
        content: |
          [Unit]
          Description=Prometheus Node Exporter
          After=network.target

          [Service]
          User=nobody
          ExecStart=/usr/local/bin/node_exporter
          Restart=always

          [Install]
          WantedBy=multi-user.target
      notify: Restart Node Exporter

    - name: Запуск и включение экспортера
      systemd:
        name: node_exporter
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Проверка версии cgroup (v1 или v2)
      command: grep cgroup /proc/mounts | head -n 1
      register: cgroup_version
      changed_when: false

    - name: Определение версии cgroup
      set_fact:
        cgroup_v2: "{{ 'cgroup2' in cgroup_version.stdout }}"

    - name: Логирование версии cgroup
      debug:
        msg: "Используется cgroup v2: {{ cgroup_v2 }}"

    - name: Запуск cAdvisor для cgroup v1
      docker_container:
        name: cadvisor
        image: google/cadvisor:latest
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
        volumes:
          - "/:/rootfs:ro"
          - "/var/run:/var/run:rw"
          - "/sys:/sys:ro"
          - "/var/lib/docker/:/var/lib/docker:ro"
      when: not cgroup_v2

    - name: Запуск cAdvisor для cgroup v2
      docker_container:
        name: cadvisor
        image: gcr.io/cadvisor/cadvisor:latest
        state: started
        restart_policy: always
        privileged: yes
        devices:
          - "/dev/kmsg:/dev/kmsg"
        ports:
          - "8080:8080"
        volumes:
          - "/:/rootfs:ro"
          - "/var/run:/var/run:rw"
          - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
          - "/var/lib/docker/:/var/lib/docker:ro"
      when: cgroup_v2

  handlers:
    - name: Restart Node Exporter
      systemd:
        name: node_exporter
        state: restarted
